name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_BUILD: "cp37-* cp38-* cp39-* cp310-* cp311-* cp312-* pp39-* pp310-*"
          CIBW_ARCHS_MACOS: "arm64 x86_64"
          CIBW_TEST_COMMAND: "python -m pymunk.tests"
          CIBW_BUILD_VERBOSITY: 3
      - uses: actions/upload-artifact@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          path: ./wheelhouse/*.whl
          retention-days: 7
  build_wasm:
    name: Build wheels for wasm / emscripten
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.2"
      - run: |
          pip install pyodide-build>=0.23.3
          echo EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version) >> $GITHUB_ENV
      - uses: mymindstorm/setup-emsdk@v12
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}
      - run: pyodide build
      - uses: actions/upload-artifact@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          path: ./dist/*.whl
          retention-days: 7
